{
    'name': "OW AI Assistant",
    'summary': "Agentic AI assistant for Odoo Community on any OpenAI-compatible provider",
    'version': '19.0.2.1.2',
    'category': 'Productivity/AI',
    'author': 'Openworx',
    'website': 'https://www.openworx.nl',
    'license': 'LGPL-3',
    'images': ['static/description/screenshot_chat.png'],
    'depends': ['mail', 'base_setup'],
    'external_dependencies': {
        'python': ['markdown2'],
    },
    'data': [
        'security/ow_ai_groups.xml',
        'security/ir.model.access.csv',
        'security/ow_ai_rules.xml',
        'data/ir_config_parameter.xml',
        'data/ow_ai_tools.xml',
        'data/ow_ai_skills.xml',
        'data/ow_ai_agent.xml',
        'data/ow_ai_composer.xml',
        'data/ir_cron.xml',
        'views/res_config_settings_views.xml',
        'views/ow_ai_preview_templates.xml',
        'views/ow_ai_usage_views.xml',
        'views/ow_ai_session_views.xml',
        'views/ow_ai_job_views.xml',
        'views/ow_ai_agent_views.xml',
        'views/ow_ai_skill_views.xml',
        'views/ow_ai_tool_views.xml',
        'views/ow_ai_composer_views.xml',
        'views/ow_ai_menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ow_ai/static/src/core/common/**/*',
            'ow_ai/static/src/core/public_web/**/*',
            'ow_ai/static/src/discuss/**/*',
            'ow_ai/static/src/web/**/*',
            'ow_ai/static/src/scss/ow_ai_chat.scss',
        ],
        'web.assets_web_dark': [
            'ow_ai/static/src/scss/ow_ai_chat.dark.scss',
        ],
        'mail.assets_public': [
            'ow_ai/static/src/core/common/**/*',
            'ow_ai/static/src/core/public_web/**/*',
            'ow_ai/static/src/discuss/**/*',
            'ow_ai/static/src/scss/ow_ai_chat.scss',
        ],
        'web.assets_unit_tests': [
            'ow_ai/static/tests/**/*',
            ('remove', 'ow_ai/static/tests/tours/**/*'),
        ],
        'web.assets_tests': [
            'ow_ai/static/tests/tours/**/*',
        ],
    },
    'application': True,
    'installable': True,
}
